/**
 * @description This class is a wrapper for SQX Applications throwing any generic errors
 * usage: new SQXApplicationGenericException(String message)
 * ******************************Revision History******************************
 * [FLEX-33] Training - Training's assignment via JF Requirement
 * ******************************Revision History******************************
 */
public class CQ_FLEX_ApplicationGenericException extends Exception {
 public static Boolean test = false;
}